# A sample Gemfile
source "https://rubygems.org"

# gem "rails"
gem "colorize"
gem "net", :require => "ftp", :require => "http", :require => "smtp", :require => "ping", :require => "https"
gem "logger"
gem "configparser"
gem "nokogiri"
gem "digest", :require => "md5"
gem "rest_client"
gem "json"
gem "filesize"
gem "whois"
#gem "fileutils"
